name: ebook publishing
favicon: null
layout_spectrum: 0.21424546255730093
typography_spectrum: 0.8302219451870769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5867164684459567
  lightness: 0.28743423405103385
  saturation: 0.3685098581481725
  rhythmicContrast: 0.6761931264773011
purpose: []
